### ISSUE TITLE
Data disk storage accounts

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/MPP_TemplatesVersion2.0#1]
For the data disks, the final template will need to make sure to use separate storage account either for each VM or for group of VMs. Currently, the template points to the same storage as the OS disk. This is ok for testing. However, in the real template it would be important to use multiple storage accounts for the data disks. Therefore, this approach of creating the data disk URLs in the variables section may not work in the long term - https://github.com/btprabhu/MPP_TemplatesVersion2.0/blob/18fb661129861b0bfa8ddce9f3021b7680c9e04d/main_Template_StaticIP.json#L238

Example here shows one way on how to use multiple storage accounts in round-robin fashion:
https://github.com/arsenvlad/snappydata-azure/blob/master/mainTemplate.json#L336
https://github.com/arsenvlad/snappydata-azure/blob/master/mainTemplate.json#L1129

**Comment by btprabhu** [comment]
I have changed this and used the StorageNameArray and create disk URLs in round-robin fashion.
