### ISSUE TITLE
Must use protectedSettings when passing secrets

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/MPP_TemplatesVersion2.0#3]
Since this template passes a secret password to the custom script extension, the commandToExecute must be placed inside of protectedSettings JSON object.

Keep the fileUris in the settings - https://github.com/btprabhu/MPP_TemplatesVersion2.0/blob/18fb661129861b0bfa8ddce9f3021b7680c9e04d/main_Template_StaticIP.json#L586

Add protectedSettings and move commandToExecute there. See example here https://github.com/Azure/azure-quickstart-templates/blob/c0861b5cf371d8b8d4ff833b230582c845d8a5e9/301-custom-images-at-scale/download.json

**Comment by btprabhu** [comment]
I have used the protected settings for passes  secret password to the custom script extension in commaneToExcute .
