### ISSUE TITLE
artifactsBaseUrl should be the base pass of all artifacts

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/MPP_TemplatesVersion2.0#5]
artifactsBaseUrl parameter should be the base pass of all artifacts. In this template, it points to a completely separate base path that contains the scripts. However, if there would be nested-templates that are in this repo directly the base path wouldn't point to them.

https://github.com/btprabhu/MPP_TemplatesVersion2.0/blob/18fb661129861b0bfa8ddce9f3021b7680c9e04d/main_Template_StaticIP.json#L7

**Comment by btprabhu** [comment]
I have used it just for testing. I will changed it when using nested template for market place solution.
