### ISSUE TITLE
Not necessary to create multiple diagnostic storage accounts

### ISSUE THREAD

**Issue by arsenvlad** [btprabhu/MPP_TemplatesVersion2.0#6]
Since storage accounts is a limited resource (i.e. you can only have up to 100 by default in a subscription), it is not advisable to create complete separate storage accounts for diagnostics of each VM. It is OK and sufficient to have all VMs use the same standard storage account (premium is not supported).

Therefore, this loop shouldn't be there. https://github.com/btprabhu/MPP_TemplatesVersion2.0/blob/master/main_Template_StaticIP.json#L274

**Comment by btprabhu** [comment]
I have removed  the looping in storage account diagnostics for each VM.
